# Generated by Django 2.2.12 on 2020-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
