# Generated by Django 3.0.4 on 2020-03-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=30)),
                ('contactNo', models.IntegerField()),
                ('subject', models.ManyToManyField(to='app31.CourseModel')),
            ],
        ),
    ]
