# Generated by Django 3.0.4 on 2020-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('network_id', models.IntegerField(primary_key=True, serialize=False)),
                ('network_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=150)),
                ('user_contact', models.IntegerField()),
                ('user_network', models.ManyToManyField(to='app32.NetworkModel')),
            ],
        ),
    ]
