# Generated by Django 3.0.4 on 2020-04-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('addr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('bank_name', models.CharField(max_length=20)),
                ('acc_no', models.IntegerField(primary_key=True, serialize=False)),
                ('branch_no', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_address', models.TextField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app35.Employee')),
            ],
        ),
    ]
