# Generated by Django 3.0.4 on 2020-04-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='emp_images/'),
            preserve_default=False,
        ),
    ]
