# Generated by Django 3.0.4 on 2020-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
