# Generated by Django 3.0.4 on 2020-04-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app41', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownersmodel',
            name='status',
        ),
    ]
