# Generated by Django 2.2.12 on 2020-05-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30, unique=True)),
                ('item_price', models.FloatField()),
                ('item_image', models.ImageField(upload_to='item_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WaiterModel',
            fields=[
                ('waiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('tbl_no', models.IntegerField()),
                ('eat_item', models.ManyToManyField(to='hotel.MenuModel')),
            ],
        ),
    ]
