# Generated by Django 2.2.12 on 2020-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='oid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
