# Generated by Django 3.0.4 on 2020-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('pname', models.CharField(max_length=30, unique=True)),
                ('pprice', models.FloatField()),
                ('pimg', models.ImageField(upload_to='products_images')),
            ],
        ),
    ]
