# Generated by Django 3.0.4 on 2020-04-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salart', models.FloatField()),
                ('photo', models.ImageField(upload_to='emp_images')),
                ('address', models.TextField()),
            ],
        ),
    ]
