# Generated by Django 3.0.4 on 2020-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app36', '0002_auto_20200405_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
