# Generated by Django 3.0.4 on 2020-04-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app36', '0005_auto_20200405_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='photo',
            field=models.ImageField(upload_to='emp_images/'),
        ),
    ]
