# Generated by Django 3.0.4 on 2020-04-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='emp_imgs')),
            ],
        ),
    ]
