# Generated by Django 3.0.4 on 2020-03-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiryaniType',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Biryani',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('biryani_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app33.BiryaniType')),
            ],
        ),
    ]
