# Generated by Django 3.0.4 on 2020-04-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRNno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('dateOfApplication', models.DateField()),
            ],
        ),
    ]
