# Generated by Django 3.0.4 on 2020-04-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30, unique=True)),
                ('pprice', models.FloatField()),
                ('pimg', models.ImageField(upload_to='product_imgs/')),
            ],
        ),
    ]
