# Generated by Django 2.2.12 on 2020-04-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app45', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='aid',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='sid',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='teachersmodel',
            old_name='tid',
            new_name='_id',
        ),
    ]
