# Generated by Django 3.0.2 on 2020-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('uname', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
