# Generated by Django 2.2.12 on 2020-04-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassdModel',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('t_idno', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('t_gender', models.CharField(max_length=10)),
                ('t_contact', models.IntegerField(unique=True)),
                ('t_add', models.TextField()),
                ('t_doj', models.DateField()),
                ('t_img', models.ImageField(upload_to='teacher_images')),
                ('t_class', models.ManyToManyField(to='admin_app.ClassdModel')),
                ('t_sub', models.ManyToManyField(to='admin_app.SubjectModel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('s_idno', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('s_gender', models.CharField(max_length=10)),
                ('s_contact', models.IntegerField(unique=True)),
                ('s_add', models.TextField()),
                ('s_img', models.ImageField(upload_to='student_images/')),
                ('s_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.ClassdModel')),
            ],
        ),
        migrations.AddField(
            model_name='classdmodel',
            name='c_subjects',
            field=models.ManyToManyField(to='admin_app.SubjectModel'),
        ),
    ]
