# Generated by Django 2.2.12 on 2020-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_teachermodel_t_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='s_password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
