# Generated by Django 3.0.2 on 2020-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('job', models.CharField(max_length=30)),
            ],
        ),
    ]
