# Generated by Django 3.0.4 on 2020-04-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='districtModel',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stateModel',
            fields=[
                ('cno', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TalukaModel',
            fields=[
                ('tno', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=30)),
                ('population', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app34.districtModel')),
            ],
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app34.stateModel'),
        ),
    ]
