# Generated by Django 3.0.4 on 2020-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('username', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('interest', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
